#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

. $HOME/.profile

systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

dunst >> /tmp/dunst.log &
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v polybar)" ]; then
    polybar --config=$HOME/.config/polybar/config.ini mainbar &
fi
exit 0
