#!/usr/bin/env bash
export $(dbus-launch)

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


echo dunsting
tmux new-session -ds main-bg
tmux new-window dunst

# if [ -x "$(command -v feh)" ]; then
    # feh --bg-fill "$SCRIPTPATH/wallpaper.jpg"
# fi

echo loading
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v polybar)" ]; then
    pkill polybar
    monitors="$(polybar -m | sed s/:.*// | tac)"
    while read -r display; do
        MONITOR=$display polybar --config=$HOME/.config/polybar/config.ini mainbar &> /dev/null &
    done <<< "$monitors"
    exit 0
fi
