#!/usr/bin/env bash
export $(dbus-launch)
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

. $HOME/.profile

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

start-bg-proc dunst

# if [ -x "$(command -v feh)" ]; then
    # feh --bg-fill "$SCRIPTPATH/wallpaper.jpg"
# fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v polybar)" ]; then
    monitors="$(polybar -m | sed s/:.*// | tac)"
    while read -r display; do
        start-bg-proc "polybar --config=$HOME/.config/polybar/config.ini mainbar" -e "MONITOR=$display" 
    done <<< "$monitors"
fi
exit 0
