import argparse
import os
import shutil
import subprocess
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from setup.runner import REGISTRY
from setup.versions import check_all, dump, load

from .registry import TOOLS

_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_SETUP_DIR = _ROOT / "setup"
_DOCS_DIR = _ROOT / "docs"
_REPORT_PATH = _DOCS_DIR / "upgrade-report.md"
_IMAGE = "diencephalon-upgrade-test:latest"
_DOCKERFILE_LEVEL1 = _SETUP_DIR / "tests" / "Dockerfile.level1"

# Derived from REGISTRY: version-tracked tools at level 0–1 that have a setup step
_DOCKER_TESTABLE: frozenset[str] = frozenset(
    s.name for s in REGISTRY if s.level < 3 and s.name in TOOLS
)


@dataclass
class ToolResult:
    name: str
    old_tag: str
    new_tag: str
    changed: bool
    test_status: str  # "passed" | "failed" | "skipped" | "no_docker"
    detail: str = ""


def _docker_available() -> bool:
    return shutil.which("docker") is not None


def _build_image() -> tuple[bool, str]:
    r = subprocess.run(
        ["docker", "build", "-t", _IMAGE, "-f", str(_DOCKERFILE_LEVEL1), "."],
        cwd=_ROOT,
        capture_output=True,
        text=True,
    )
    return r.returncode == 0, (r.stdout + r.stderr).strip()


def _run_verify() -> tuple[bool, str]:
    r = subprocess.run(
        [
            "docker",
            "run",
            "--rm",
            _IMAGE,
            "python3",
            "-m",
            "setup",
            "verify",
            "--level",
            "1",
        ],
        capture_output=True,
        text=True,
        timeout=300,
    )
    return r.returncode == 0, (r.stdout + r.stderr).strip()


def _parse_step_results(output: str) -> dict[str, str]:
    """Parse `setup verify` output into {step_name: status}."""
    results: dict[str, str] = {}
    for line in output.splitlines():
        line = line.strip()
        if line.startswith("[ ok ]"):
            results[line[7:].strip()] = "passed"
        elif line.startswith("[FAIL]"):
            name = line[7:].split(":")[0].strip()
            results[name] = "failed"
    return results


def _write_report(
    results: list[ToolResult],
    build_output: str,
    verify_output: str,
    docker_ok: bool,
    token_used: bool,
) -> None:
    _DOCS_DIR.mkdir(exist_ok=True)
    today = date.today().isoformat()

    lines: list[str] = [
        f"# Upgrade Report — {today}",
        "",
        "_Generated by `dienpy versions upgrade-system --test`_",
        "",
    ]
    if not token_used:
        lines += ["**Warning:** no GITHUB_TOKEN set — GitHub rate limits apply.", ""]

    lines += [
        "## Version Summary",
        "",
        "| Tool | Was | Latest | Changed |",
        "|------|-----|--------|---------|",
    ]
    for r in results:
        changed = "YES" if r.changed else "—"
        lines.append(f"| {r.name} | {r.old_tag} | {r.new_tag} | {changed} |")

    lines += ["", "## Docker Test (levels 0–1)", ""]
    if not _docker_available():
        lines += ["Docker not available on this host.", ""]
    elif not build_output and not verify_output:
        lines += ["No docker-testable tools changed.", ""]
    elif docker_ok:
        lines += ["Build and verify succeeded.", "", "```", verify_output[-4000:], "```", ""]
    else:
        lines += [
            "**Docker test failed.**",
            "",
            "### Build output",
            "```",
            build_output[-3000:],
            "```",
            "",
            "### Verify output",
            "```",
            verify_output[-2000:],
            "```",
            "",
        ]

    skipped = [r for r in results if r.test_status == "skipped"]
    if skipped:
        lines += ["## Skipped — QEMU required (levels 3+)", ""]
        for r in skipped:
            entry = TOOLS.get(r.name)
            lvl = entry.level if entry else "?"
            lines.append(f"- **{r.name}** (level {lvl}): {r.old_tag} → {r.new_tag}")
        lines += [""]

    pm = [r for r in results if r.test_status == "no_docker"]
    if pm:
        lines += ["## Package-manager managed (no Docker test)", ""]
        for r in pm:
            if r.changed:
                lines.append(f"- **{r.name}**: {r.old_tag} → {r.new_tag}")
            else:
                lines.append(f"- **{r.name}**: {r.new_tag} (unchanged)")
        lines += [""]

    lines += [
        "## Next steps",
        "",
        "To apply updates to live system:",
        "```",
        "dienpy versions upgrade-system --live",
        "```",
        "",
        "To revert toml if tests failed:",
        "```",
        "git checkout setup/versions.toml",
        "```",
    ]

    _REPORT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Report written to {_REPORT_PATH}")


def cmd_test(token: str | None) -> None:
    updates = check_all(token)
    today = date.today().isoformat()

    versions = load()
    for tv, latest in updates:
        if tv.tag != latest:
            versions[tv.name].tag = latest
            versions[tv.name].checked = today
    dump(versions)

    results: list[ToolResult] = []
    for tv, latest in updates:
        entry = TOOLS.get(tv.name)
        changed = tv.tag != latest
        level = entry.level if entry else 99

        if level >= 3:
            status = "skipped"
        elif tv.name in _DOCKER_TESTABLE:
            status = "pending"
        else:
            status = "no_docker"

        results.append(
            ToolResult(
                name=tv.name,
                old_tag=tv.tag,
                new_tag=latest,
                changed=changed,
                test_status=status,
            )
        )

    build_output = ""
    verify_output = ""
    docker_ok = False
    pending = [r for r in results if r.test_status == "pending"]

    if pending and _docker_available():
        print(f"Building Docker test image from {_DOCKERFILE_LEVEL1.name}...")
        build_ok, build_output = _build_image()
        if not build_ok:
            print("Docker build failed.")
            for r in results:
                if r.test_status == "pending":
                    r.test_status = "failed"
                    r.detail = "image build failed"
        else:
            print("Running setup verify in container...")
            docker_ok, verify_output = _run_verify()
            step_results = _parse_step_results(verify_output)
            for r in results:
                if r.test_status == "pending":
                    r.test_status = step_results.get(
                        r.name, "passed" if docker_ok else "failed"
                    )
    elif pending:
        for r in results:
            if r.test_status == "pending":
                r.test_status = "no_docker"

    _write_report(results, build_output, verify_output, docker_ok, token is not None)


def cmd_live() -> None:
    versions = load()
    for tv in versions.values():
        entry = TOOLS.get(tv.name)
        if entry is None:
            print(f"[ -- ] {tv.name}: no installer")
            continue

        if not tv.installed and entry.check:
            already = (
                subprocess.run(entry.check, shell=True, capture_output=True).returncode
                == 0
            )
            if already:
                print(f"[init] {tv.name}: marking installed at {tv.tag}")
                versions[tv.name].installed = tv.tag
                dump(versions)
                continue

        if tv.tag == tv.installed:
            print(f"[skip] {tv.name}")
            continue

        fn = entry.upgrade_fn or entry.install_fn
        print(f"[ >> ] {tv.name}: {tv.installed or 'uninstalled'} → {tv.tag}")
        try:
            fn()
            versions[tv.name].installed = tv.tag
            dump(versions)
            print(f"[ ok ] {tv.name}")
        except Exception as e:
            print(f"[FAIL] {tv.name}: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(prog="dienpy versions upgrade-system")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--test",
        action="store_true",
        help="fetch latest versions, bump toml, test in Docker, write report",
    )
    group.add_argument(
        "--live",
        action="store_true",
        help="install tools whose pinned version differs from installed",
    )
    parser.add_argument("--token", default=os.environ.get("GITHUB_TOKEN"))
    args = parser.parse_args()

    if not args.token and args.test:
        print("warning: no GITHUB_TOKEN — rate limited to 60 req/hr")

    if args.test:
        cmd_test(args.token)
    else:
        cmd_live()


def get_completions(args: list[str]) -> list[str]:
    if not args:
        return ["--test", "--live", "--token"]
    return []
